name: MT5 Trading Bot

on:
  schedule:
    - cron: "0 * * * *"  # Runs hourly
  workflow_dispatch:     # Allows manual runs

jobs:
  run-bot:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      
      - name: Install dependencies
        run: |
          pip install MetaTrader5 python-dotenv
          sudo apt-get install -y wine  # Required for MT5 Linux compatibility
      
      - name: Run trading bot
        env:
          MT5_ACCOUNT_ID: ${{ secrets.MT5_ACCOUNT_ID }}
          MT5_PASSWORD: ${{ secrets.MT5_PASSWORD }}
          MT5_SERVER: ${{ secrets.MT5_SERVER }}
        run: |
          python -c "import os; print('Account ID:', os.getenv('MT5_ACCOUNT_ID'))"  # Verify secrets
          python your_bot_file.py
